services:
  runner:
    image: "abdullin/tga-runner:latest"
    command: --args="-p 10000 -c /var/benchmarks/gitbug/benchmarks.json -t 120 -o /var/results --runs 1"
    networks:
      - shared-network
    volumes:
      - ./results:/var/results

  tool:
    image: "abdullin/tga-tools:latest"
    command: --args="--ip runner --port 10000 --tool kex"
    networks:
      - shared-network
    volumes:
      - ./results:/var/results

volumes:
  shared-volume:

networks:
  shared-network:
    driver: bridge
